FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    alembic==1.15.2 \
    sqlalchemy==2.0.41 \
    psycopg2-binary==2.9.9 \
    pydantic-settings==2.9.1

COPY . .

CMD ["alembic", "upgrade", "head"]
